eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8065
spring:
  application:
    name: product_type_db
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
